# Python 

**Overview **

Python is a cross-platform programming language, which means it runs on all the major operating systems. Any Python program you write should run on any modern computer that has Python installed. However, the methods for setting up Python on different operating systems vary slightly.

Python originated in the late 1980s and its main goal is to be readable by human beings (not only machines!). This is why it
looks simpler than other programming languages.

Python is used for creating websites, scientific software, graphics, and games and also applied in data science.

**Variables**

A variable is a name for something so you can use it later. Programmers use these variables to store data, make their code more readable.

Variables have to be specific and are also case sensitive. 

Variable names can contain only letters, numbers, and underscores.

Spaces are not allowed in variable names, but underscores can be used to separate words in variable names

Examples:



In [1]:
name ='Kofi'
age = 12
country_1= 'Ghana'
sum = 12.5

> Note that: name =’Kofi’ is different from Name=’Kofi’ and different from names =’Kofi’

**Strings**

Strings is a data type used to represent text or a series of characters. Anything inside quotes can be considered as a string in Python. You can use single (‘ ’) or double quotes (“ ”) around your strings.

Examples:

In [2]:
x = "Hello"
y = 'My name is …'
t = 'python programmer'

*Changing Case in Strings*

One of the simplest tasks you can do with strings is change the case of the
words in a string.

![https://i.imgur.com/bK2beW6.jpg](https://i.imgur.com/bK2beW6.jpg)


In [3]:
t= 'imagine dragons'

*Combining or Concatenating Strings*

The + symbol is used to combine strings. This method of combining strings is called concatenation. You can use concatenation to compose complete messages using the information you’ve stored in a variable.
Example:


In [4]:
print("Hello" + "How are you?")
x= 'I am ' 
y= 'happy'
z= print(x+y)

HelloHow are you?
I am happy


> Note that, if you need to put an apostrophe inside your string, you have two ways to do it.  

“Theirs is a big cat on the fence”

‘And she said “I like it” ’

**Number**

Number data types store numeric values. They are immutable data types. This means, changing the value of a number data type results in a newly allocated object. Numbers are not kept in quotes 

Examples:


In [5]:
x= 1
y= 345

![https://i.imgur.com/7okc0iW.jpg](https://i.imgur.com/7okc0iW.jpg)

**Floats**

Float is a number that has both an integer and fractional part, separated by a point (Decimals). 

Examples:

In [6]:
print(0.1 + 0.1)
print(0.4)
print(2 * 0.1)

0.2
0.4
0.2


**Lists**

A list is a collection of items in a particular order. A list is represented by [] and individual elements in the list are separated by commas.

Examples:

In [7]:
fruits = ['apple', 'orange' ,'pear', 'banana']
num= [1, 4, 7, 5, 90, 3]

*Organizing a List*

Often, your lists will be created in an unpredictable order, because you can’t always control the order in which your users provide their data. Although this is unavoidable in most circumstances, you’ll frequently want to present your information in a particular order. Sometimes you’ll want to preserve the original order of your list, and other times you’ll want to change the original order. Python provides a number of different ways to organize your lists, depending on the situation.

![https://i.imgur.com/Gcx3HGE.jpg](https://i.imgur.com/Gcx3HGE.jpg)

*Accessing Elements in a List*

Lists are ordered collections, so you can access any element in a list by telling Python the position, or index, of the item desired. To access an element in a list, write the name of the list followed by the index of the item enclosed in square brackets.


In [8]:
print(fruits[0])
print('My favorite fruits is' +' '+ fruits[2].title())

apple
My favorite fruits is Pear


*Index Position*

Python considers the first item in a list to be at position 0, not position 1.The second item in a list has an index of 1. Using this simple counting system, you can get any element you want from a list by subtracting one from its position in the list. For instance, to access the fourth item in a list, you request the item at index 3.

*Simple Statistics with a List of Numbers*

A few Python functions are specific to lists of numbers. For example, you can easily find the minimum, maximum, and sum of a list of numbers.

![https://i.imgur.com/7fqYBnZ.jpg](https://i.imgur.com/7fqYBnZ.jpg)

*Modifying Elements in a List*

![https://i.imgur.com/gvRdmpr.jpg](https://i.imgur.com/gvRdmpr.jpg)

**Dictionaries**

A dictionary is similar to a list, but you access values by looking up a key instead of a numeric index. A key can be any string or number. A dictionary is represented by {}.

Example:


In [9]:
users = {'name': 'Kofi', 'country': 'Ghana', 'age': 12} 

> With this command, you just created a variable named users with three key–value pairs:
> The key name points to the value 'Kofi' (a string object),country points to 'Ghana' (another string ),and  age points to 12 (a number).

*Accessing Values in a Dictionary*

To get the value associated with a key, give the name of the dictionary and then place the key inside a set of square brackets.

Example:


In [10]:
print(users['age'])

12


*Modifying Values in a Dictionary*

![https://i.imgur.com/OkuB0sv.jpg](https://i.imgur.com/OkuB0sv.jpg)

**Conditional Statements**

Programming often involves examining a set of conditions and deciding which action to take based on those conditions. In Python you can compare things by using > , >= , == , <= , < and the and , or operators.

*If and else Statements*

Python’s if statement allows you to examine the current state of a program and respond appropriately to that state.

Examples:

In [11]:
if 3>2:
	print('it works') 
else:
	print('Not True')

it works


elif is used to handle more than one condition. 

Examples:

In [12]:
name= 'Kofi'
if name == 'Yaw':
	print('Hi Yaw')
elif name == 'Kofi':
	print('Hi Kofi')
else:
	print('Hi anonymous')

Hi Kofi


> See what happened there? elif lets you add extra conditions that run if the previous conditions fail. You can add as many elif statements as you like after your initial if statement.

In [13]:
volume = 56
if  volume < 28:
	print('It is quiet')
elif  28<= volume <= 48:
	print('It is nice for background music')
elif 48<= volume <=68:
	print('Perfect I can hear all the details')
else:
	print('My ears are hurting')

Perfect I can hear all the details


*Comparison Operator*

![https://i.imgur.com/inZ7Fte.jpg](https://i.imgur.com/inZ7Fte.jpg)

*Boolean and Logical Operators*

There are only 2 Boolean operators.
* True
* False

But for Python to understand this, you need to always write it as 'True' (first letter uppercase, with the rest of the letters lowercased). true, TRUE, and tRUE won't work – only True is correct. (The same applies to 'False' as well.)

Assuming a holds True and b holds False then:

![https://i.imgur.com/sMcyTFE.jpg](https://i.imgur.com/sMcyTFE.jpg)

**Classes**

A user-defined prototype for an object that defines a set of attributes that characterize any object of the class. The attributes are data members (class variables and instance variables) and methods, accessed via dot notation.
Classes represent real world things and situations

*Creating a class*

The class statement creates a new class definition. The name of the class immediately follows the keyword class followed by a colon.

Example:

In [14]:
class Employee:
   def __init__(self, name, salary):
      self.name = name
      self.salary = salary   
   def displayEmployee(self):
      print ("Name : ", self.name,  ", Salary: ", self.salary)

*Creating Instance Objects*

To create instances of a class, you call the class using class name and pass in whatever arguments its init method accepts.


In [15]:
# This would create first object of Employee class
emp1 = Employee("Zara", 2000)
# This would create second object of Employee class
emp2 = Employee("Manni", 5000)

*Accessing Attributes*

To access the attributes of an instance, you use dot notation.

Examples:


In [16]:
emp1.name
print("Employee’s name is :  " + emp1.name )

Employee’s name is :  Zara


*Accessing Method*

After we create an instance from the class Dog, we can use dot notation to call any method defined in Employee.

Example:

In [17]:
emp2.displayEmployee()

Name :  Manni , Salary:  5000


# **Numpy**

NumPy is a Python library that can be used for scientific and numerical applications and is the tool to use for linear algebra operations. 

*Creating Numpy Array:*

Numpy arrays can be easily manipulated and are faster in computation.

Np.arange([start],[stop],[step]) returns a list which starts at [start] and ends at [stop] with an interval of [step]. 

In [18]:
import numpy as np # linear algebra

#A = normal array; B = array with zeros; C=identity matrix
A = np.array([1,2,3,4,5,6]) 
B = np.zeros((3,3))
C = np.eye(3)

#Using arrange
np.arange(0,20,2)

#Reshaping A to multi-dim 2 by 3 matrix/array
D = A.reshape(2,3)

print(A)
#print(B)
#print(C)
#print(D)

[1 2 3 4 5 6]


Arrays = Vectors=matrix so from Example 1, the shape of the Array = 5 (A.shape) or in normal math terms a 1✕5 matrix. This matrix can be changed to a multiple dimensional array by using reshape also in example 1.
2D and Nd arrays

*Numpy.ndarray:* An array object represents a multidimensional, homogeneous array of fixed-size items. An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size. The number of dimensions and items in an array is defined by its shape, which is a tuple of N positive integers that specify the sizes of each dimension. The type of items in the array is specified by a separate data-type object (dtype), one of which is associated with each ndarray. 

Accepted parameters: 
1. Shape: Shape of created array. 
1. Dtype: Any object that can be interpreted as a numpy data type.
1. Buffer: Used to fill the array with data.
1. Offset: Offset of array data in buffer.
1. Strides: Strides of data in memory.
1. Order: Row-major (C-style) or column-major (Fortran-style) order.


In [19]:
np.ndarray((2,), buffer = np.array([4,5,6]), offset=np.int_().itemsize, dtype=int)

array([5, 6])

**Numpy Methods**

![https://i.imgur.com/vqC8WmZ.jpg](https://i.imgur.com/vqC8WmZ.jpg)



**Statistics with Numpy**

*Mean*

Compute the arithmetic mean along the specified axis. Returns the average of the array elements. The average is taken over the flattened array by default, otherwise over the specified axis. float64 intermediate and return values are used for integer inputs.

How: numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)


In [20]:
np.mean(D)               #calculates mean of flattened array
#np.mean(D, axis=0)       #calculates mean along the 0-axis
#np.mean(D, axis=1)       #calculates mean along the 1-axis


3.5

*Median*

Compute the median along the specified axis. Returns the median of the array elements.

How: numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)


In [21]:
np.median(D, axis=1)	#computes median along a certain axis

array([2., 5.])

*Standard Deviation (Std)*

Compute the standard deviation along the specified axis. Returns the standard deviation, a measure of the spread of a distribution, of the array elements. The standard deviation is computed for the flattened array by default, otherwise over the specified axis.

How: numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>)


In [22]:
np.std(D, axis=0)	#calculates std of D along 0-axis

array([1.5, 1.5, 1.5])

*Pearson Product-Moment correlation coefficients (Corrcoef)*

Return Pearson product-moment correlation coefficients.

How: numpy.corrcoef(x, y=None, rowvar=True, bias=<no value>, ddof=<no value>)


In [23]:
np.corrcoef(D)

array([[1., 1.],
       [1., 1.]])

*Sum*

Sum of array elements over a given axis.

How: numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>)

In [24]:
np.sum(D, axis=1)	#calculates sum along rows/1-axis

array([ 6, 15])

*Sort*
Return a sorted copy of an array.

How: numpy.sort(a, axis=-1, kind='quicksort', order=None)

In [25]:
np.sort(D)		#sort along the last axis

array([[1, 2, 3],
       [4, 5, 6]])

*Random.normal*

Draws random samples from a normal (Gaussian) distribution.

How: numpy.random.normal(loc=0.0, scale=1.0, size=None)


In [26]:
mu, sigma = 0, 0.1
np.random.normal(mu, sigma, 1000)

array([ 5.92533867e-04, -1.35991188e-02,  1.39097907e-01, -1.88678381e-01,
        1.54681710e-01, -6.24411330e-02, -1.65531203e-01, -4.74157595e-02,
       -1.65900265e-01,  1.58693829e-01,  3.07055470e-02,  1.05475784e-02,
       -5.05688487e-02, -1.83910786e-01,  5.61736161e-03, -5.80335667e-02,
        5.70744488e-02,  1.92298978e-01, -2.68188889e-01,  2.30856007e-02,
       -6.26325801e-02,  4.53976079e-02,  2.94420104e-03,  2.40205696e-03,
       -4.76710709e-02,  6.55579188e-02, -1.56173136e-01, -4.60102571e-02,
        7.13696126e-03,  8.58503795e-02, -3.68282642e-02, -6.78789273e-02,
        1.36355487e-01, -5.24394311e-02, -1.25993990e-01, -5.88610423e-02,
        1.17292577e-01, -1.44215004e-01, -7.94398110e-02,  6.80098909e-02,
       -1.86438968e-01, -3.69955892e-02, -1.84962060e-01, -1.54338200e-01,
        1.72836257e-01,  2.61986598e-01, -2.57888709e-02, -6.85941972e-02,
        1.11624304e-01,  1.63537412e-01, -4.00144720e-02,  5.31582399e-02,
       -5.63151561e-02, -

*Round*

Round an array to the given number of decimals.

How: numpy.round_(a, decimals=0, out=None)


In [27]:
np.round_(D)

array([[1, 2, 3],
       [4, 5, 6]])

*Boolean and Logical Operators*

Unsure if referring to truth value testing and logical operations here :https://docs.scipy.org/doc/numpy/reference/routines.logic.html 

**Resources: **

1. https://hackernoon.com/introduction-to-numpy-1-an-absolute-beginners-guide-to-machine-learning-and-data-science-5d87f13f0d51

1. https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.html

1. https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-manipulation.html

1. https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html


# **Pandas**

It supports reading and writing excel spreadsheets, CVS's. It also helps you to manage two-dimensional data tables in Python.

**Series and Dataframes**

*Series*

A pandas Series is a one dimensional data structure (“a one dimensional ndarray”) that can store values and for every value it holds a unique index.



In [28]:
import pandas as pd
G = pd.Series([1,2,2,4,5,8,9,5,2])
print(G)

0    1
1    2
2    2
3    4
4    5
5    8
6    9
7    5
8    2
dtype: int64


**DataFrame**

A pandas DataFrame is a two (or more) dimensional data structure, basically a table with rows and columns. The columns have names and the rows have indexes.

*Reading and Writing Files*

![https://i.imgur.com/XdGYXir.jpg](https://i.imgur.com/XdGYXir.jpg)


Source: https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-read-csv-table

In [29]:
#pd.read_csv('zoo.csv', delimiter = ',')		#Reading a csv file with delimiter “,”

# B is loading csv file with headers being specified
B = pd.read_csv('pandas_tutorial_read.csv', delimiter=';', names = ['my_datetime', 'event', 'country', 'user_id', 'source', 'topic'])
#B

**Column, row selection & Subnetting**

In [30]:
# Selecting and displaying a column as dataframe
#B[['user_id']]
#B[['user_id', 'topic']]		#Selected two columns

# Selecting and displaying a column as series
#B[‘user_id’]
#B.user_id

# Selecting rows of country 1
#B.country == 'country_1'

# Selection by Position
#B.iloc[3]

# Selecting explicit value
#B.iloc[2,3]


**Adding, deleting, modifying column, rows, specific locations(Element access)**

https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html#merging-concatenation 

https://data36.com/pandas-tutorial-3-important-data-formatting-methods-merge-sort-reset_index-fillna/

https://data36.com/pandas-tutorial-2-aggregation-and-grouping/

**Calculating new columns from existing columns**


**Resources:**

1. https://data36.com/pandas-tutorial-1-basics-reading-data-files-dataframes-data-selection/

1. https://hackernoon.com/intro-to-pandas-1-an-absolute-beginners-guide-to-machine-learning-and-data-science-a1fed3a6f0f3

1. https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html#merging-concatenation 

1. https://data36.com/pandas-tutorial-3-important-data-formatting-methods-merge-sort-reset_index-fillna/

1. https://data36.com/pandas-tutorial-2-aggregation-and-grouping/
